language: go

go:
- 1.2
- tip

before_install:
- export PATH=$HOME/gopath/bin:$PATH
- go get github.com/tools/godep

install:
- godep restore
- godep go install github.com/onsi/ginkgo/ginkgo

script:
- ginkgo -r