language: go

go:
- 1.2
- tip

env:
  global:
    secure: ZBqQnFYuf0qyL4kg5nF6kKy/wpgdp2/Fcxx43/hktulNI9jjxs/XUm22Jzy00jgAJImoxTFzd6EVR5AAX84pcwHrozAu5ZAX6lmuDmvKn0aFQONZLx+S6KP8rmPGbbjJHP5wSpNfMONNrzaAsQ2+aKaiNYqOfYJ4MgcMsAL4nTE=

before_install:
- export PATH=$HOME/gopath/bin:$PATH
- export PATH=$PWD/Godeps/_workspace/bin:$PATH
- export GOPATH=$PWD/Godeps/_workspace:$GOPATH

install:
- go get -v github.com/mattn/goveralls
- go get code.google.com/p/go.tools/cmd/cover
- go install github.com/onsi/ginkgo/ginkgo

script:
- ginkgo -r -cover

after_success:
- 'echo "mode: set" > all.coverprofile'
- 'find . -name "*.coverprofile" -exec grep -v mode: {} >> all.coverprofile \;'
- goveralls -coverprofile=all.coverprofile -repotoken=$COVERALLS_TOKEN
